### PR TITLE
Fixes

### LINKED ISSUE #394: Hyena Bomber DBS-32C action bar
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** Wave 3 stuff is up but may not be accurate.

### Expected Behavior

Hyena Class Droid Bomber DBS-32C has a red jam action instead of red reload

### Actual Behavior

Shows red reload action instead of red jam action

### Language

The affected language(s).

### PR DESCRIPTION
**Pull request by Patschke**
Closes #394

### CODE REVIEW

**Comment by Patschke** [comment]
Not 100% sure about the last commit: It will allow to use Angled Deflectors on a TIE Interceptor, if you also equip a shield upgrade. IMO this should be correct, but if you feel it is a wrong ruling you may revert this commit.

**Comment by raithos** [comment]
Im pretty sure thats not allowed, so I'm going to revert the last one but yeah lets commit this

**Comment by Patschke** [comment]
I guess it will be pure random whether the official squad builder will allow doing so or will not... For actions it is perfectly fine to meet a requirement by use of another upgrade (e.g. one need to equip a turret to be allowed to take VTG), so I can't see why it would not be fine for stats as well...

**Comment by Patschke** [comment]
However, as the number of zero shield ships having more than one modification slot available is rather small, and I don't think the combination is that usefull on a TIE-Interceptor, it won't matter in the end ;-)

**Comment by raithos** [comment]
you might be right from a technical standpoint, but I don't think that's the intent. We have the code so in 2 weeks if we find the official app is doing it, we can always roll it back in.

**Pull request merged**
