### PR TITLE
Closing some Issues

### LINKED ISSUE #473: left  bid to stop randomizing is ignored
### Expected Behavior

'left bid to stop randomizing' value should be subtracted from total points and randomizer should not generate a squad with more points than 'max - bid'

### Actual Behavior

randomizer generates a squad with a max point value somewhere near the max value, sometimes at max value, apparently ignoring the 'left bid' value

suggest removing this feature, as one can specify a max value of, e.g. 195 instead of 200 points to get a 5 point bid

if feature remains after fix, suggest renaming or adding an info popup/bubble icon since it took me days to figure out what this feature meant.

### Language

English

### PR DESCRIPTION
**Pull request by Patschke**
Closes #473

### CODE REVIEW

**Comment by Patschke** [comment]
closes #472

**Comment by Patschke** [comment]
closes #471

**Comment by Patschke** [comment]
Closes #470

**Comment by Patschke** [comment]
I've noticed that there is a crazy speed difference in running the random generator depending on whether you are logged in. It is so significant, that it probably points us towards some nasty code, that slows down yasb overall (not only during random generation) - so it might be worth inverstigating this further.

**Comment by raithos** [comment]
So i noticed that if you randomize quick builds while collection only is selected, it doesnt generate any ships because the quickbuilds are untethered from the collection. I think if we wanted collections to work with quickbuilds we would have to check to see if they own the ship

**Comment by Patschke** [comment]
Quickbuilds actually exist as cards, so it would also be an option to include them to the expansions. This would result in nobody owning the pdf only quickbuilds, but is maybe more conveniant for newbies (for whom quickbuilds are meant)? Not sure though who is actually using quickbuilds...

**Pull request merged**
