### PR TITLE
Correct Error with Boba Fett Upgrade Slots

### PR DESCRIPTION
**Pull request by JaredRoth**

### CODE REVIEW

**Comment by raithos** [comment]
Im confused because this is already how it is?

**Comment by JaredRoth** [comment]
Ok... now I'm confused. How can there be a diff in the PR if that's already how it is?
Sorry, I had thought the PR was self-explanatory.
YASB 2.0 has Boba Fett with two modification slots and no crew slot. In reality, he should have one of each (like every other pilot of that ship). This PR corrects that.

**Comment by skitau** [comment]
@JaredRoth Latest points update replaced just Boba's crew slot with an additional modification slot.

image

**Comment by JaredRoth** [comment]
Ah, I see. You're all more on top of it than me. Thanks, and sorry!

**Comment by skitau** [comment]
All good buddy. Last points change and hyperspace shake up was very different. Thanks for keeping an eye out!

**Pull request closed without merging**
