### PR TITLE
Bugfixes and Issue closing

### LINKED ISSUE #442: Link to details when "You cannot field this list with your collection!"
### Expected Behavior

I expect to hover or click on the "You cannot field this list with your collection!" message to see which cards my collection is short, perhaps even see a list of what to buy to allow the list.

### Actual Behavior

Nothing. The text is just plain text.

### Language

The affected language(s).

### PR DESCRIPTION
**Pull request by Patschke**
Closes #442

### CODE REVIEW

**Comment by raithos** [comment]
I'm going to hold of on any commits right now until the huge ship stuff is pushed. theres a lot of changes so I want to make sure thats deployed first in case of conflicts

**Comment by Patschke** [comment]
Sure. I'll resolve any possible merge conflicts as soon as you push that.

**Comment by Patschke** [comment]
Closes #446

**Comment by Patschke** [comment]
Just added the changes suggested in #445. I think we should update somewhere on those lines in  case that works for everybody?

If you feel like this needs a deeper review, I'll reverse that commit, and make it a separate PR (as its nature is different from the feature/bugfix commits also included in this PR).

**Comment by Patschke** [comment]
Closes #452 
Closes #451

**Comment by Patschke** [comment]
Closes #453

**Pull request merged**
