### PR TITLE
Removed damage cards translation

### PR DESCRIPTION
**Pull request by Thunderpombo**
translation was not happening, couldn't find why.

### CODE REVIEW

**Comment by Patschke** [comment]
There have been two issues: 
  * all the Starter Pack translations are added in the section for chassis translations (instead of pilot translations)
  * the damage translations have not been added to the export (last line in the file). 

After fixing those issues, the translations work fine for me. 

image

Since I've fixed these for me, I can open a PR for that.

**Comment by Thunderpombo** [comment]
Nice, sorry for that, but some things are being translated (like ship names and chassi), and the pilot names and abilities are not

 



De: Patrick Mischke ***@***.***> 
Enviada em: segunda-feira, 21 de agosto de 2023 04:55
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Removed damage cards translation (PR #1321)

 

There have been two issues:

*	all the Starter Pack translations are added in the section for chassis translations (instead of pilot translations)
*	the damage translations have not been added to the export (last line in the file).

After fixing those issues, the translations work fine for me.

 <https://user-images.githubusercontent.com/17853362/261956556-332fd08e-4093-4b2c-9307-1ef2686516d7.png> 

Since I've fixed these for me, I can open a PR for that.

**Comment by Patschke** [comment]
Well, I don't think that you were supposed to merge this... It actually just removes translations, whereas my PR was including them properly...

**Comment by Thunderpombo** [comment]
The second part on text on the new Outrider title for YT-2400 shoud read “you may change...” instead of “you may spend...”

**Pull request merged**
