### PR TITLE
Wave 4

### PR DESCRIPTION
**Pull request by godgremos**
cards-common.coffee has not changed (I can't remove from pull request)

### CODE REVIEW

**Comment by raithos** [comment]
i dont understand the changes made to cards-common.coffee, can you explain them to me?

**Comment by Patschke** [comment]
There are no changes to `cards-common.coffe` done by this PR? Maybe some commit does some changes, which are undone subsequently - but `cards-hu.coffee` is the only file changed by this PR

**Comment by raithos** [comment]
yeah when i first looked at it there were some weird file changes to cards-common, which is why i asked. seeing as those are gone now, ill happily commit

**Comment by raithos** [comment]
@godgremos watch your indenting, I just caught a compile error because one line was 1 space off from the rest of the items. coffeescript is really strict with its indenting

**Comment by gmodos** [comment]
Sorry guys, a couple months ago I changed and uploaded cards.common.coffe but didn't committed.
Now I've finished Wave 4 translations and couldn't get rid of changed cards.common.coffe. My best idea was to change it to the latest version. I only know upload/pull request method on Github, nothing more.
@raithos roger, roger

**Pull request merged**
