### PR TITLE
Update english ship names and implements #180

### LINKED ISSUE #177: Official Ship Names Instead of Arbitrary Names
### Expected Behavior
I expect the squadron builder's names to reflect the names in the official products.
### Actual Behavior
The squadron builder's names do not reflect the names in the official products.
### Language
English (at least)

### PR DESCRIPTION
**Pull request by Patschke**
engilsh ship names are now official 2nd edition ship names. We still use YASB
names internally.

Closes #177

### CODE REVIEW

**Comment by raithos** [comment]
I actually have an issue with this. I specifically do not like the official names using their titles, makes it actually difficult to find stuff. An X-Wing should be an X-Wing. It's so fussy to rename everything. You're going to have to give me some time to get over this before i merge it.

**Comment by Patschke** [comment]
I understand your point. Having e.g. an A-Wing named RZ-1 A-Wing is awful (and there are quite a few rebel ships having that issue). On the other hand, I can also see, that, for new 2nd edition players, it could be hard to tell, that a TIE Advanced Prototype might be a v1, while a TIE Advanced is supposed to be the x1 - as the old name is not beeing used at all anymore.

**Comment by raithos** [comment]
Yeah. just give me until the end of the week to mourn the old names

**Comment by raithos** [comment]
:(

**Pull request merged**
