### PR TITLE
Things Done

### PR DESCRIPTION
**Pull request by Patschke**
#312 and #295 and #308

### CODE REVIEW

**Comment by Patschke** [comment]
Also #297 (removed custom mode)

**Comment by raithos** [comment]
will merge this tonight just a bit busy right now

**Comment by Patschke** [comment]
There've been some new official spoilers one could add recently, did not have much time to do so either.

How was the System Open?

**Comment by raithos** [comment]
I'll take care of those tonight when I push this. The SO was great. Had a lot of fun and some really intense games. We have a great community

**Comment by zacharyp** [comment]
this broke yasb2-xws :(

**Comment by zacharyp** [comment]
Please don't change the url versioning without maybe telling me first, or a PR on that project as well!

**Comment by Patschke** [comment]
Sorry, I'll try to keep that in mind. We discussed somewhere, that we wanted to rework the custom mode, so i thought it would be cleaner to increment the version code for that.

**Pull request merged**
