### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by Kharnete**
Created the Spanish translation for YASB 2.0.

I've used Patschke's script for the main work so I don't expect any issues on that part. If any problem appears on the rest, I'll quickly fix it just as I did on YASB 1.0 (or at least, I will once I wake up :P)

### CODE REVIEW

**Comment by Kharnete** [comment]
Welp, I shouldn't do these things at late, late night XD. I checked all the things listed at the ToDo file, but for some reason I didn't see the wrong part on any of that (which is ridiculous in some cases like the dual cards. I mean, I *had* to know for sure that YASB only uses one card for them just like on 1.0 XD).

Working on all this right now.

**Comment by Patschke** [comment]
The yasb name is `Servomotor S-Foils` (capital F).

**Comment by Kharnete** [comment]
Just saw it while comparing with the DE translation :)

**Comment by Patschke** [comment]
Just saw it when reading the error message :)

LGTM, it compiles and runs fine, so the PR should be ready to be merged. I do not speak any spanish, so I can't comment on the actual translations

**Pull request merged**
