### PR TITLE
Edrio and Benthic do not have hyphens in their names.

### PR DESCRIPTION
**Pull request by sirjorj**

### CODE REVIEW

**Comment by Patschke** [comment]
Basically you are right, we do simply use the names from the cards. For the ships we stuck to the 1st edition names in some cases. I think you should have a look at the xws spec for your project, it does define a exchange format used by yasb, LaunchBay, list juggler and some other projects. 

It is also possible to load some data directly from ffg, but that data does also contain quite a lot of mistakes. You may want to look at our jsonDownloader.py for that. 

Having more accurate data is always a good thing. If you happen to have quickbuild data you are more than welcome to parse them into the format of #298

**Comment by Patschke** [comment]
In general I think we should use names like they are written on the cards. You are welcome to correct any mistakes you find. However there are some intended exceptions, e.g. double sided cards. For the ships the names in yasb basically were never changed, and are still the simpler names that were written on the cards in 1.0. As long as I don't see a benefit of changeing them, I'll not put work into that. If you want to do that, go ahead and do so...

If you have any questions regarding the data layout of yasb feel free to ask. I don't think that we will benefit that much from using some shared data source, as we want to include all kinds of spoiler and incomplete card texts as early as possible. Nevertheless having a validation will never hurt.

**Comment by sirjorj** [comment]
I fully agree with that last part.  There are multiple different data libraries for xwing for different uses/platforms.  My goal is not to unify them into one, but to compare their values against each other to eliminate typos and data errors.

**Comment by raithos** [comment]
Going to close this pull request for the time being. If we're going to be connecting the databases between all the different formats, I don't think we need to rewrite all the names, xws exists as a format to act as a go-between all the different programs, so I'd rather make sure our xws names are compliant rather than rename a bunch of our stuff.

**Comment by Patschke** [comment]
Using a name as key has some advantages over using an id: It is human readable. So e.g. for adding new Quickbuild cards, it is much easier to add them if we can just copy in all the pilot and upgrade names, and do not need to look up the ids for those cards in our own database. The same holds true for the translation files: It is much easier to find translation mistakes, if the cards are referenced by name instead of by id. Basically it comes down to: For data definition names are used, as it is easier to input new data that way, and for internal references that are computed during runtime the id is used as key. 

I don't think we are opposed to having "somebody" change the name keys to the names on the card, but are not willing to spend our own time onto that - it will not directly improve any functionality, so at least I am personally not going to do that. 
I am for sure not trying to prevent you from finding mistakes in our database, that is obviously more than welcome. 

As we are currently adding quickbuilds to yasb, I wondered whether you would be able to set up a parser for the other direction: From your database into our format (cards-common.coffee somewhere about line ~9000). That way we would not need to copy + paste the data from the pdfs manually. 

If you find any mistakes in the data of yasb you are welcome to report them as an issue. If you want to create pull requests that fixes those mistakes, thats of course welcome, too - but those PR should be complete enough to be merged in without breaking anything. That was not the case for this PR, so it was treated like an issue: The mistakes have been corrected in d22c45e7adfc7decb07b2a811a68e5f5f99898c2 and this PR has been closed. 

As you noticed we calculate xws data as needed when sombody hits the export as xws button. As xws is an format that contains not only names, but is supposed to be used for exporting whole squads, it is always neccessary to create the correct structure of pilots and upgrades belonging to those pilots (together with stuff like a squad name, ...). Thus, one needs a method doing that anyway, and we never had a reason for not creating the xws name just inside there. You may find that method in line 2331 of xwing.coffee. 
For the pure xws names it comes down to: 
a) xws property if set (e.g. Hera Syndulla (VCX) has set it directly in cards-common.coffee)
b) canonical_name
where the canonical_name, if not set directly, is computed as the canonicalized version of the name property. Canonicalize is a simple function 
```
String::canonicalize = ->
    this.toLowerCase()
        .replace(/[^a-z0-9]/g, '')
        .replace(/\s+/g, '-')
```
So if you want to match our cards to your card database, a possible option could be computing the xws name from our data just like that, and comparing to your database after you done that .

**Pull request closed without merging**
