### PR TITLE
Accessibility suggestions

### PR DESCRIPTION
**Pull request by norbyyt1300**
Adding increased spacing between elements, coloring backgrounds to provide higher contrast, changing button colors to highlight warning / optional actions, all just through styling additions.

I'm a huge fan of the app, and just was thinking of a few slight tweaks that could help a small subset of users find the UI a little easier to use.  Don't get me wrong, it's absolutely amazing as is, and I don't want to suggest anything otherwise--I just happen to do a little bit of UI work for my job, and so I at least wanted to make these suggestions in case you happen to be making a merge sometime soon.  I know there are more elegant ways to make these edits, but at least this way, they're hopefully pretty easy to parse out what they do.  Thanks for your consideration!

### CODE REVIEW

**Comment by Patschke** [comment]
As I have no idea on how to provide proper UX/UI, I am always happy to receive any constructive feedback. If that feedback is in the form of a PR, I'm even more happy!

I like the look, so my only critic point might be, that I don't like the name `new-common-spacing`, as it will keep that name forever ;-)

**Comment by norbyyt1300** [comment]
Thanks!  Good catch on the variable name; using a var to keep the spacing consistent might've seemed like a good idea, but yes, that name will likely not be relevant/accurate in the long term, so hard-coded 10px might be better.  And some of the navbar buttons fall into two main groups, the faction buttons and the other, non-faction buttons, so I split those into two groups as well, to make it easier for folks to focus on the faction selection without risk of selecting a non-faction button.

**Comment by Patschke** [comment]
I'm not against a variable there. Just name it `common-spacing` instead of `new-common-spacing`

Your design: 

grafik

Current design:

grafik

The background images are just missing cause I'm lazy. 

I'm not sure if I like the black box grouping some of the stuff at the top - I can't see a reason why that should be grouped together semantically. The new top bar looks imo better than our current design. I like it.

**Comment by norbyyt1300** [comment]
Got it.  I've reverted to using a var for spacing, but now using the better name you suggested.

And thanks! And for that dark background for the squad name, points, and print / random button, I totally messed up--I forgot to commit the right file.  Now it might make more sense; since this is a dark theme, we want to draw the user's eye using a gradient of shades, from the most static content (the top nav bar, now a much darker shade) to the squad name and points (a slightly less dark shade) to where they should focus most of their attention, the central area where the squad content resides, which is the lightest shade.  Sorry, earlier without the shades in the right order it probably didn't make any sense.

**Comment by raithos** [comment]
Will go live later today. Is there any conflicts with the mobile version? I'm assuming not but thought I'd ask

**Comment by norbyyt1300** [comment]
@raithos Thanks!  It passed all of the by-hand tests when viewed in mobile mode, so I think we should be alright.  Just curious--is there a mobile testing framework that you use?

**Pull request merged**
