### PR TITLE
Ships in Browser and hiding texts on printout

### LINKED ISSUE #262: Print Layout easy/fancy
Hy,
is it possible to make an option in the simple text mode or in the fancy mode to see the ship stat`s in a way you see in the picture?
Because there are no more informations of the ship stat`s and availabe actions on the ship base pat, the simple Layout is a bit to simple ;-)

Maybe it`s possible to create a checkbox in the fancy mode to skip the text of the upgrade cards. Or you can add the stat`s and actions of the ships in the ship/pilot field in the simple mode.

simple-fancy

Thanks! Keep up the great work!

### PR DESCRIPTION
**Pull request by Patschke**
Adds ships as Item of the card browser. 
Implements text hiding. 

Close #262

### CODE REVIEW

**Comment by Patschke** [comment]
Added a quite usefull change of the translation files. If a language does not yet contain a translation of a card, it will use the english (and subsequently polish) translation instead. Thus we no longer need to add spoiler to each language file, but only to the language the spoiler has been released in (usually english or polish), .

**Comment by Patschke** [comment]
Ran translation script to fix #260 

English is now sorted alphabetically for all officially released cards again.

**Comment by raithos** [comment]
I cant merge this, running the english script has removed hardpoints and all unreleased ships.

**Comment by raithos** [comment]
well ok maybe not the hardpoints, but the unreleased content still seems to be eliminated?

**Comment by raithos** [comment]
delta-7b was the marker for me that was missing, which i just realized is an upgrade. so maybe its upgrades that are getting erased?

**Comment by Patschke** [comment]
I've been readding them. I did check from the bottom of the new upgrades, to find the first one that has already been released by now (which was the pattern analyzer), and expected everything above to be released as well. That assumption was wrong, there were another few upgrades above that are still unreleased. 

I think I've now added all back in. Sorry for the mistake.

**Comment by raithos** [comment]
No problem, thanks for getting it fixed :)

**Pull request merged**
