### PR TITLE
quickbuild fixes

### PR DESCRIPTION
**Pull request by sirjorj**

### CODE REVIEW

**Comment by raithos** [comment]
i assume this was handled in the other pull request

**Comment by Patschke** [comment]
I actually don't think so. While this PR was 99% whitespace changes that had no effect at all, there have been like two actual changes in upgrades (e.g. stuff like Proton Torps instead of Plasma Torps), which were probably mistakes on creating the quickbuilds. Not sure how many changes I missed, as all the whitespace stuff cluttered up the diff. 

I've included this commit in my latest PR, though I'd prefere having a readable diff where I do not have to search for the actual changes...

**Comment by raithos** [comment]
I scrubbed through your commit and yeah it was only white space left. All the other stuff was in the other commit which I already merged

**Comment by Patschke** [comment]
Ah, OK. I thought the "other pr" was my last quick build pr. Didn't notice the changes you made. Sorry for the confusion

**Pull request closed without merging**
