### PR TITLE
Enable display of card sources, add second edition sources

### PR DESCRIPTION
**Pull request by johndeboer**
PR to update the manifest file with new core, conversion kits, and wave 1 expansions.  

Enables card source display in the tooltip and card browser.

image

image

### CODE REVIEW

**Comment by raithos** [comment]
I'll commit these to live when I get back on Sunday

**Comment by johndeboer** [comment]
I added another commit with small changes to card text, upgrades, and the expert handling points.

**Comment by raithos** [comment]
these changes are now live! TY for helping out! small note, when you added the cards, some of the names didnt match up but I fixed those quickly :) collections now working fully thanks to your time :D

**Comment by johndeboer** [comment]
That's great, glad to help.  Thank you for taking over this project for 2.0!

**Pull request merged**
