### PR TITLE
Update cards-pt.coffee

### PR DESCRIPTION
**Pull request by Thunderpombo**
Pilot cards translated

### CODE REVIEW

**Comment by Patschke** [comment]
Two minor issues (https://github.com/Patschke/xwing/commit/0be2585eb1aff73be56e35b912dc20e2c5a1884c), otherwise it runs fine.

**Comment by Thunderpombo** [comment]
Sorry, I’ve just Only understood what I should have done after I submitted the second PR haha

 

De: Patrick Mischke ***@***.***> 
Enviada em: segunda-feira, 10 de abril de 2023 14:59
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

Two minor issues (Patschke@ <https://github.com/Patschke/xwing/commit/0be2585eb1aff73be56e35b912dc20e2c5a1884c> 0be2585), otherwise it runs fine.

**Comment by Thunderpombo** [comment]
Nice, I saw that you put it online, but for some reason, Only the Rebel pilots are apperaring in portuguese here

 

De: raith ***@***.***> 
Enviada em: sexta-feira, 14 de abril de 2023 11:47
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

Merged #1255 <https://github.com/raithos/xwing/pull/1255>  into master.

**Comment by raithos** [comment]
i found it.         "Cartel Marauder": was missing an extra space. it was misaligned with the rest of the array

**Comment by Thunderpombo** [comment]
Nice, I’ll fix it na put an icon text I’ve forgot on an upgrade, thanks

 

De: raith ***@***.***> 
Enviada em: sexta-feira, 14 de abril de 2023 13:48
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

i found it. "Cartel Marauder": was missing an extra space. it was misaligned with the rest of the array

**Comment by raithos** [comment]
actually, there are a lot of indent issues. im fixing them all but please be careful to ensure that all indents are the same across all entries

**Comment by Thunderpombo** [comment]
Ok, I’ll let you do that then, sorry for that...

 

De: raith ***@***.***> 
Enviada em: sexta-feira, 14 de abril de 2023 13:56
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

actually, there are a lot of indent issues. im fixing them all but please be careful to ensure that all indents are the same across all entries

**Comment by Thunderpombo** [comment]
A question, when you do that on your file, it updates mine, or I need to update mine aswell?

 

De: raith ***@***.***> 
Enviada em: sexta-feira, 14 de abril de 2023 13:56
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

actually, there are a lot of indent issues. im fixing them all but please be careful to ensure that all indents are the same across all entries

**Comment by raithos** [comment]
ok ive fixed the formatting issues, i noticed youre missing a few pilots still, seems like all of the st-70 pilots and dooku (SoC) and maybe more

**Comment by raithos** [comment]
ive pushed my changes, so you just have to sync to the latest version and you should get all the changes I made.

**Comment by Thunderpombo** [comment]
Cool, about the missing pilots, you are right, probably skipped them, thanks for the warning

 

De: raith ***@***.***> 
Enviada em: sexta-feira, 14 de abril de 2023 14:03
Para: raithos/xwing ***@***.***>
Cc: Thunderpombo ***@***.***>; Author ***@***.***>
Assunto: Re: [raithos/xwing] Update cards-pt.coffee (PR #1255)

 

ive pushed my changes, so you just have to sync to the latest version and you should get all the changes I made.

**Pull request merged**
